# Generated by Django 5.0 on 2024-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_alter_product_type_delete_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
