# Generated by Django 5.0.6 on 2024-06-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
    ]
