# Generated by Django 5.0.6 on 2024-07-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carusel',
            new_name='Carusel_up_to_five_images',
        ),
    ]
